# Generated by Django 5.0.1 on 2024-01-31 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user_master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empcode", models.IntegerField(auto_created=True)),
                ("empname", models.CharField(max_length=50)),
                ("designation", models.IntegerField(blank=True, null=True)),
                ("department", models.IntegerField(blank=True, null=True)),
                ("password", models.CharField(max_length=50)),
                ("rolename", models.CharField(max_length=50)),
                ("createdby", models.CharField(max_length=50)),
                (
                    "jn_date",
                    models.DateField(blank=True, default="0000-00-00", null=True),
                ),
                (
                    "lv_date",
                    models.DateField(blank=True, default="0000-00-00", null=True),
                ),
                ("dob", models.DateField(blank=True, default="0000-00-00", null=True)),
                ("mail_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "external_mail",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "personal_mail",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("mail_indi", models.CharField(blank=True, max_length=50, null=True)),
                ("gndr", models.IntegerField(default=1)),
                ("QMS", models.IntegerField(default=1)),
                ("SAP", models.IntegerField(default=1)),
                ("crnt_sts", models.IntegerField(default=1)),
                ("mgr", models.IntegerField(blank=True, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=10, null=True)),
                ("phno", models.IntegerField(blank=True, null=True)),
                ("loc", models.CharField(blank=True, max_length=50, null=True)),
                ("empgroup", models.CharField(blank=True, max_length=20, null=True)),
                ("empsubgroup", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "payscale_grade",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "payscale_level",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "payscale_sub_level",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("pay_range", models.CharField(blank=True, max_length=20, null=True)),
                ("adapt", models.CharField(blank=True, max_length=20, null=True)),
                ("empType", models.CharField(blank=True, max_length=50, null=True)),
                ("extn", models.CharField(blank=True, max_length=50, null=True)),
                ("shrt", models.CharField(blank=True, max_length=50, null=True)),
                ("active_name", models.CharField(blank=True, max_length=10, null=True)),
                ("photo_sts", models.IntegerField(blank=True, default=0, null=True)),
                ("build_no", models.CharField(blank=True, max_length=10, null=True)),
                ("room_no", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "local_std_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("sys_no", models.CharField(blank=True, max_length=15, null=True)),
                ("loc_outstn", models.CharField(blank=True, max_length=50, null=True)),
                ("gl", models.CharField(blank=True, max_length=60, null=True)),
                ("tl", models.IntegerField(blank=True, null=True)),
                ("level_1", models.IntegerField(blank=True, null=True)),
                ("level_2", models.IntegerField(blank=True, null=True)),
                ("company_id", models.IntegerField(blank=True, null=True)),
                ("tprog", models.CharField(blank=True, max_length=20, null=True)),
                ("timestamp", models.DateTimeField(default=datetime.datetime.now)),
                ("delete1", models.IntegerField(default=0)),
                ("marital_status", models.IntegerField(default=0)),
                ("tms_status", models.IntegerField(default=0)),
                ("ass_role", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "qualification",
                    models.CharField(
                        blank=True, default="SSC", max_length=20, null=True
                    ),
                ),
                ("empcode_md5", models.CharField(blank=True, max_length=50, null=True)),
                ("tr_facility", models.CharField(blank=True, max_length=10, null=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "marriage_date",
                    models.DateField(blank=True, default="0000-00-00", null=True),
                ),
                ("phone_permission", models.CharField(default=0, max_length=20)),
                (
                    "bus_route",
                    models.CharField(blank=True, default=0, max_length=10, null=True),
                ),
                ("ext_status", models.CharField(blank=True, max_length=10, null=True)),
                ("work_loc", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "audit_emp_sts",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "auditor_qua_date",
                    models.DateField(blank=True, default="0000-00-00", null=True),
                ),
                (
                    "auditor_disqua_date",
                    models.DateField(blank=True, default="0000-00-00", null=True),
                ),
                ("uan", models.CharField(blank=True, max_length=20, null=True)),
                ("pan", models.CharField(blank=True, max_length=20, null=True)),
                ("bank_indi", models.CharField(blank=True, max_length=500, null=True)),
                ("bank_acc", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "attendance_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("ess", models.CharField(blank=True, max_length=10, null=True)),
                ("alt_contact", models.CharField(blank=True, max_length=20, null=True)),
                ("ot_flag", models.CharField(blank=True, max_length=20, null=True)),
                ("rsc", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "db_table": "user_master",
            },
        ),
    ]
